import { ThemeContext, ThemeContextProvider } from "@/context/ThemeContext";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { useContext } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <AuthContextProvider>{children}</AuthContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
